name: CI
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    uses: palashmon/reusable-workflows/.github/workflows/main-build-legacy.yml@main